VECTORS

In [1]:
import numpy as np

In [2]:
v = np.array([2, 1])

In [3]:
# Create a 2x2 identity matrix representing the standard basis vectors
basis = np.eye(2)
print('Standard Basis Vector:\n',basis)

Standard Basis Vector:
 [[1. 0.]
 [0. 1.]]


In [4]:
# Create a 2x2 identity matrix representing the standard basis vectors
basis = np.eye(2)
print('Standard Basis Vector:\n',basis)

Standard Basis Vector:
 [[1. 0.]
 [0. 1.]]


In [ ]:
# Compute the basis vectors using the coefficients
basis_vectors =( coefficients * basis)
print('Basis vectors for above coefficients:\n',basis_vectors)

Find the standard basis vector for the same vector space

In [6]:
import numpy as np
 
u = np.array([6, 5, 8, 11])
 
magnitude_u = np.linalg.norm(u)
unit_vector_u = u / magnitude_u
 
basis_vectors = []
for i in range(len(unit_vector_u)):
    if unit_vector_u[i] != 0:
        basis_vectors.append(np.eye(len(unit_vector_u))[i])
 
basis_vectors = np.array(basis_vectors)
basis_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

COMBINING

In [7]:
# Lets us now concatenate 3 vectors.
#In this example, we have created 3 vectors vec1,vec2,vec3 using sample function and then concatenate the vectors into a single vector using the concatenate function
vec1 <- sample (0:9 , 50 , replace = TRUE)
vec2 <- sample(0:4 , 25 ,replace = TRUE)
vec3 <- sample(1:3 , 15 , replace = TRUE)
 
c(vec1,vec2,vec3)

SyntaxError: invalid syntax (105768641.py, line 3)